DATASET_PATH = '../Datasets/SpeedSignsForDkPrecise/'
MAX_EPOCHS = 250
BATCH_SIZE = 8
ACCUMULATE_GRAD_BATCHES = 10
LEARN_RATE = 0.0001 # Learning rate
LEARN_RATE_BACKBONE = 0.00001 # Learning rate backbone
WEIGHT_DECAY = 0.0001
GRADIENT_CLIP = 0.1
CONFIDENCE_TRESHOLD = 0.5
IOU_TRESHOLD = 0.8
MODEL_PATH = 'DETR_trained_version_0'
NUM_WORKERS = 20 # Recommended to num of cores
CHECKPOINT = 'facebook/detr-resnet-50'
