DATASET_PATH = '../Datasets/SpeedSignsForEUMedium/'
MAX_EPOCHS = 400
BATCH_SIZE = 10
ACCUMULATE_GRAD_BATCHES = 12
LEARN_RATE = 0.0001 # Learning rate
LEARN_RATE_BACKBONE = 0.00001 # Learning rate backbone
WEIGHT_DECAY = 0.0001
CONFIDENCE_TRESHOLD = 0.5
IOU_TRESHOLD = 0.8
MODEL_PATH = 'custom-model'
NUM_WORKERS = 20 # Recommended to num of cores
CHECKPOINT = 'facebook/detr-resnet-50'
